apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service  # Nombre del Deployment
spec:
  replicas: 2  # Número de réplicas
  selector:
    matchLabels:
      app: frontend-service  # Etiqueta para seleccionar los Pods
  template:
    metadata:
      labels:
        app: frontend-service  # Etiqueta del Pod
    spec:
      containers:
      - name: frontend  # Nombre del contenedor
        image: eljhovaflores/frontend-service:latest  # Imagen de Docker
        ports:
        - containerPort: 80  # Puerto del contenedor
        envFrom:
        - secretRef:
            name: frontend-secret 